# Generated by Django 2.2.6 on 2019-10-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescription_medicine',
            unique_together={('prescription', 'medicine')},
        ),
    ]
